DROP SEQUENCE IF EXISTS FOOD_LOG_SEQ;
DROP TABLE IF EXISTS FOOD_LOG;
DROP TABLE IF EXISTS USER_PROFILE;
DROP TABLE IF EXISTS authorities;
DROP TABLE IF EXISTS users;

CREATE SEQUENCE FOOD_LOG_SEQ START WITH 100;

CREATE TABLE users(
    username varchar_ignorecase(50) not null primary key,
    password varchar_ignorecase(250) not null,
    enabled boolean not null
);

CREATE TABLE authorities (
    username varchar_ignorecase(50) not null,
    authority varchar_ignorecase(50) not null,
    constraint fk_authorities_users foreign key(username) references users(username)
);
create unique index ix_auth_username on authorities (username,authority);


CREATE TABLE USER_PROFILE (
  USER_NAME varchar_ignorecase(50) not null  PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  WEIGHT DOUBLE,
  HEIGHT DOUBLE,
  AGE INT,
  DAILY_CALORIES_LIMIT INT DEFAULT 2000
);

CREATE TABLE FOOD_LOG (
  ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
  USER_NAME varchar_ignorecase(50) not null,
  "DATE" DATE NOT NULL,
  "TIME" TIME NOT NULL,
  TEXT VARCHAR(250) NOT NULL,
  NUMBER_OF_CALORIES DOUBLE,
  ON_TRACK BOOLEAN DEFAULT TRUE,
  CONSTRAINT FK_FOOD_LOG_USER_PROFFILE FOREIGN KEY("USER_NAME") REFERENCES USER_PROFILE("USER_NAME")
);


INSERT INTO USER_PROFILE(USER_NAME, FIRST_NAME, LAST_NAME, HEIGHT,  WEIGHT, AGE, DAILY_CALORIES_LIMIT) VALUES ('user', 'Scott', 'Tiger', 6.1, 200, 32, 2000); 
INSERT INTO USER_PROFILE(USER_NAME, FIRST_NAME, LAST_NAME, HEIGHT,  WEIGHT, AGE, DAILY_CALORIES_LIMIT) VALUES ('manager', 'User', 'Manager', 5.5, 120, 26, 1400);
INSERT INTO USER_PROFILE(USER_NAME, FIRST_NAME, LAST_NAME, HEIGHT,  WEIGHT, AGE, DAILY_CALORIES_LIMIT) VALUES ('admin', 'System', 'Admin', 5.8, 142, 42, 1600);
  
INSERT INTO FOOD_LOG(ID, USER_NAME, "DATE", "TIME", TEXT, NUMBER_OF_CALORIES) VALUES (1, 'user', '2016-05-01', '06:01:00', '2 brown bread with butter and 1 glass of milk', 800); 
INSERT INTO FOOD_LOG(ID, USER_NAME, "DATE", "TIME", TEXT, NUMBER_OF_CALORIES) VALUES (2, 'user', '2016-05-01', '12:01:00', '1 pasta', 600);
INSERT INTO FOOD_LOG(ID, USER_NAME, "DATE", "TIME", TEXT, NUMBER_OF_CALORIES) VALUES (3, 'user', '2016-05-01', '15:01:00', '2 apples', 200);
INSERT INTO FOOD_LOG(ID, USER_NAME, "DATE", "TIME", TEXT, NUMBER_OF_CALORIES) VALUES (4, 'user', '2016-05-01', '18:01:00', '1 green salad and eggs', 300);

INSERT INTO FOOD_LOG(ID, USER_NAME, "DATE", "TIME", TEXT, NUMBER_OF_CALORIES) VALUES (5, 'manager', '2016-05-01', '07:01:00', '1 cheese sandwich with 2 eggs', 600); 
INSERT INTO FOOD_LOG(ID, USER_NAME, "DATE", "TIME", TEXT, NUMBER_OF_CALORIES) VALUES (6, 'manager', '2016-05-01', '13:01:00', '1 brown rice with soup', 200);
INSERT INTO FOOD_LOG(ID, USER_NAME, "DATE", "TIME", TEXT, NUMBER_OF_CALORIES) VALUES (7, 'manager', '2016-05-01', '16:01:00', '2 banana', 300);
INSERT INTO FOOD_LOG(ID, USER_NAME, "DATE", "TIME", TEXT, NUMBER_OF_CALORIES) VALUES (8, 'manager', '2016-05-01', '19:01:00', '2 veggie pizza slice', 400);


INSERT INTO FOOD_LOG(ID, USER_NAME, "DATE", "TIME", TEXT, NUMBER_OF_CALORIES) VALUES (9, 'admin', '2016-05-01', '06:21:00', '3 pancakes', 700); 
INSERT INTO FOOD_LOG(ID, USER_NAME, "DATE", "TIME", TEXT, NUMBER_OF_CALORIES) VALUES (10, 'admin', '2016-05-01', '12:31:00', '1 cup noodle', 500);
INSERT INTO FOOD_LOG(ID, USER_NAME, "DATE", "TIME", TEXT, NUMBER_OF_CALORIES) VALUES (11, 'admin', '2016-05-01', '15:41:00', '1 mango shake', 250);
INSERT INTO FOOD_LOG(ID, USER_NAME, "DATE", "TIME", TEXT, NUMBER_OF_CALORIES) VALUES (12, 'admin', '2016-05-01', '18:58:00', '1 cup of green tea', 100);

  
COMMIT;
  